name: Publish Docker image
on:
  push:
    branches:
      - main
      - master
      - continuous-builds
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            result:
              - 'result/**'
            vote:
              - 'vote/**'
            worker:
              - 'worker/**'
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
      -
        if: steps.filter.outputs.result== 'true'
        name: Build Results
        uses: docker/build-push-action@v2
        with:
          context: ./result
          file: ./result/Dockerfile
          push: true
          tags: |
            ghcr.io/opschautari/example-voting-app:result-latest
      -
        if: steps.filter.outputs.worker== 'true'
        name: Build Worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: |
            ghcr.io/opschautari/example-voting-app:worker-latest
      -
        if: steps.filter.outputs.result== 'true'
        name: Build Vote
        uses: docker/build-push-action@v2
        with:
          context: ./vote
          file: ./vote/Dockerfile
          push: true
          tags: |
            ghcr.io/opschautari/example-voting-app:vote-latest
